# general settings
name: EARFA_x2
model_type: SRModel
scale: 2
num_gpu: 8  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub
    dataroot_lq: datasets/datasets/DIV2K/DIV2K_train_LR_bicubic/X2_sub
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/test_datasets/Set5/GTmod2
    dataroot_lq: datasets/test_datasets/Set5/LRbicx2
    io_backend:
      type: disk
      
  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/test_datasets/Set14/GTmod2
    dataroot_lq: datasets/test_datasets/Set14/LRbicx2
    io_backend:
      type: disk
      
  val_3:
    name: BSD100
    type: PairedImageDataset
    dataroot_gt: datasets/test_datasets/BSD100/GTmod2
    dataroot_lq: datasets/test_datasets/BSD100/LRbicx2
    io_backend:
      type: disk
      
  val_4:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: datasets/test_datasets/Urban100/GTmod2
    dataroot_lq: datasets/test_datasets/Urban100/LRbicx2
    io_backend:
      type: disk
      
  val_5:
    name: Manga109
    type: PairedImageDataset
    dataroot_gt: test_datasets/Manga109/GTmod2
    dataroot_lq: test_datasets/Manga109/LRbicx2
    io_backend:
      type: disk

# network structures
network_g:
  type: EARFA
  num_feat: 60
  num_blocks: 12
  upscale_attn: 2
  upscale_sgfn: 2
  dw_size_sgfn: 5
  downscale_eca: 8
  dw_size: 5
  dw_di_size: 7
  upsampler: 'pixelshuffledirect'
  img_range: 1
  upscale_sr: 2

# # path
path:
  pretrain_network_g: ~
  strict_load_g: True
  param_key_g: params_ema
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 475000, 500000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e-3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: True
      better: higher

    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      test_y_channel: true
      crop_border: 2
      better: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

